development:
  adapter: postgresql
  encoding: utf8
  database: rales_engine_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: rales_engine_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: rales_engine_production
  pool: 5
  username: 
  password:
